language: generic

matrix:
  include:
  - os: linux
    env: SYSTEM=linux
  - os: linux
    env: SYSTEM=scientific
    service: docker
  - os: osx
    env: SYSTEM=osx

before_cache:
- rm -rf $HOME/miniconda/conda-bld $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.
    - $HOME/miniconda # Add the installation to TRAVIS cache.

before_install:
- ls .
- ls ./bin/
- bash bin/run_travis_before_install.sh

install:
- ./bin/run_travis_install.sh

script:
- ./bin/run_travis_script.sh

after_success:
- codecov

deploy:
  # test pypi
  - provider: pypi
    skip_cleanup: true
    twine_version: 1.12.1
    server: https://test.pypi.org/legacy/
    user: rfechtner
    password:
      secure: f7KmjmeMlTB904EE4sd9m96KCzCUfpEmGWl8n/53of29TUrXpv92T77X1vWfzFcdAadn/FPMrQsUzqXURgTgdpsT2Zk7DFScSDewdJ0JqQwOW73ucTwFtShzsX0GFcWT4xnR6Nvz5VM1A527//mLDR/CnyCwdDRT2bLidduUZOVtytwmSst/08tH1dK/iwqB74Ks2YIPGoi0/D3JzCKKkPGQnqnr+V4Q36hBHXUIUivEMQnvCBqS63+fdfMFOlwgMUWQrxIy/BFboWmlPqgymx4j2N3C8MLjt7cEBBt5rTZXnENstjWO1CZSVvlkpv57CUuxl4AuC2Es/wtat+qkFSZOnNDU+8UNWBWrJoFtJWZWUx+Rs0S4I+e8KjDJSWwy4cqZV9tEPJdXxW5SXOzzLLbveDqJxtVEk8vqRj3CiaTic3VCjxid2sDUPIJkdNDDu1Jm1C1/wn2vOtJMze5xyuwXIzL6ySNVwdne1rTSCy/OXxH5YPoZhDmFfs2iwGq+x+txJkQMvQfvCj8K7Yrg3+ipDTRlHJUHnfrpktTUNfyry46ajDxsBa3Jl+nyuYsczFIDEC/r9boP5F893kbDMwsTHzbugn60b/2vbdC7a6RleZyqySZ8vr+ly12nP5uzqRGmK2v9qi++PIzKEVwS+aYYwnkHJqIMVh8VMCQCp3M=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME = "linux" && $PRERELEASE = "1"
  # production pypi
  - provider: pypi
    skip_cleanup: true
    twine_version: 1.12.1
    user: rfechtner
    password:
      secure: f7KmjmeMlTB904EE4sd9m96KCzCUfpEmGWl8n/53of29TUrXpv92T77X1vWfzFcdAadn/FPMrQsUzqXURgTgdpsT2Zk7DFScSDewdJ0JqQwOW73ucTwFtShzsX0GFcWT4xnR6Nvz5VM1A527//mLDR/CnyCwdDRT2bLidduUZOVtytwmSst/08tH1dK/iwqB74Ks2YIPGoi0/D3JzCKKkPGQnqnr+V4Q36hBHXUIUivEMQnvCBqS63+fdfMFOlwgMUWQrxIy/BFboWmlPqgymx4j2N3C8MLjt7cEBBt5rTZXnENstjWO1CZSVvlkpv57CUuxl4AuC2Es/wtat+qkFSZOnNDU+8UNWBWrJoFtJWZWUx+Rs0S4I+e8KjDJSWwy4cqZV9tEPJdXxW5SXOzzLLbveDqJxtVEk8vqRj3CiaTic3VCjxid2sDUPIJkdNDDu1Jm1C1/wn2vOtJMze5xyuwXIzL6ySNVwdne1rTSCy/OXxH5YPoZhDmFfs2iwGq+x+txJkQMvQfvCj8K7Yrg3+ipDTRlHJUHnfrpktTUNfyry46ajDxsBa3Jl+nyuYsczFIDEC/r9boP5F893kbDMwsTHzbugn60b/2vbdC7a6RleZyqySZ8vr+ly12nP5uzqRGmK2v9qi++PIzKEVwS+aYYwnkHJqIMVh8VMCQCp3M=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME = "linux" && $PRERELEASE = "0"
      
after_deploy:
- test $TRAVIS_OS_NAME = "linux" && test $PRERELEASE = "0" && ./bin/update_bioconda.sh
