language: python
python:
- '3.5'
- '3.6'
- 3.7-dev
cache: pip
install:
- pip install docutils
- pip install Sphinx sphinx-autodoc-typehints sphinx-rtd-theme
- pip install -e .
script:
- pytest
- rst2html.py --halt=2 README.rst >/dev/null
deploy:
  provider: pypi
  user: rfechtner
  password:
    secure: cGzhPkZ2KtdSUwgHqrcNZM56aryYHQH7Yh9tvy5jlqSPvRb8V+WzXCKtUdN1MxbK3HvSYUUPqE4NcD0iea/socAJc4r4grFu/zGirdSXBayNkkRe1gTGHyytk2Gn7tIzT/piZQGFlj9p/6tc2O2YgL/I8DqkQodZxRbUa89JaGGkFkATLBEpFpcK1lfYpc7tZrXTSy2ET5Jil1A4Z1cLXxs8788hcpLRGVxOvu3+jGUYKQU1l8FBuGyBJxmszb/pL3GOxYWqSRY89UaLGZNfsJWg/KSpCyHizki39Wq5DHkg2usdi9so8NYCxMSjECGDe8rvQxGMkyEThtwP1tzQDqWkUFBYoC7oxPaFSUGMCWTrV7Wzmovy+j6bMw+QvL8szDqZtIwIiEbv9sYrUlbkQlYrFtF3lBLx0ErZ4HZ+U3HpV56Ucl81KFIfuZLL8gktr3ZxEjv74fu/BW2gkeGolf7bxUKgNVGUh6ZVIpsIS+SwPZC9ksd41HbKAqizKRlgndTmxC3YbZNW5p+lGoQba/jVGT/q1rdqYObNJHg/33NdoVYo60K5ACY3z4/05L3sc3JyP3P+ugJWpkSlJ/qoMIMSV2comTc14OP38uHFzb3ErNkZ0FiZVYRJ9cUc3LTJirBWWkH8Hdd+al0IstX6CdUkGUhKIuACjowhgdu9yOk=
  on:
    tags: true
