language: python
python:
- '3.5'
- '3.6'
- 3.7-dev
cache: pip
install:
- pip install docutils Sphinx sphinx-autodoc-typehints sphinx-rtd-theme
- pip install -e .[plotting]
script:
- pytest
- rst2html.py --halt=2 README.rst >/dev/null
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: rfechtner
  password:
    secure: CvYZu8lcM6ruSlressxmOnsd2IwDSDt6VqHMI7xOV8UuTmg6WBcrhhFJGkStd+8J/vHsFS+7ubSVGt+a5GmtAq4Q8PNu2g28yzbN8qtr0D7bzLlE/cnst3YpHFn3IV8XpgHrUBiNvWUWd5AE3e9ZyicxAO7r5ewAMnOwu8iuq3FM3Q7gmwRFhzRMXpQjE7WGT1Xfnrnkj5Riz1vEl0qPHYI2JFdyRckHNdBfuodI05yzBDugKTrMYT5b+qBw+VAIXz6k6oi9WiQ5E5jlnqKbTo8+sixQ/5xtyprXWju5ydXxkQkdjZ2xzxlCGQ98435F/yULLnSObRMzmhgoCeLA20nztaOWN12La0itHIdiRuRYgJsPzWqq7aRv1fotFFnuh4Xw+DJg+QazKDgkI+7vAXXVajJNy5Zn+RrNgbY0Csba3jkv6HlQHM/lZK8SsaB53H05QqNn+pbWKEdGXRhgG7+GsiuOHRbKicAInCNWeaqRuIkh78aUwWQpj5nv3V993fgcDzgq2OzUv450p4PHrfS/OidUhrksXrYLf2PbglgKBqJ1AV66n1CpnD6NLm5ZXSBbkN04hWr/lCOYN98Ou9i7kMmcOYZ0awGqSbQq1jGkhUSV0yeXOSd0V70WxkTES33Smulnobph/6SOROPUxo5pRzL2WxGUAckVL7o9YH4=
  on:
    tags: true
