language: python
python:
- '3.5'
- '3.6'
- 3.7-dev
cache: pip
install:
- pip install docutils Sphinx sphinx-autodoc-typehints sphinx-rtd-theme
- pip install -e .[plotting]
script:
- pytest
- rst2html.py --halt=2 README.rst >/dev/null
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: rfechtner
  password:
    secure: E18D42GQ2oubgZ8x4D7VV2i+NWNJsGvpnc6DZY8FMTIEGdj8LY6TjTW/q4M/prdIrz9R7oARJq5B2T2fgMn1Nvz09WMQjr+sepuGe6OHjCn7X5OMOW33n5YaIHs3bihLHpcKCqFdloYtOlNmOS3gjdM6zr2BDsFyTMhpmZuxm1zUJxTfECPvtY94RC8qVhC36pnjizh2STeeFrI2YDjl7I/8tVgox7zFv9lWUFz9k9mFuEXVc+hUMnaPgRnYZvd96NhGA8esgI8tjEoLnj49NclIp0CaF95SfVP+h91pEAgEuX766f8R3DcKhrIuMvUFTsHicDxEZq7mvBoaUsnLXoWZTZEkN+bv+VwCQbbb892RrV96RuG/Sb9kdy4P9/rpPhvkQghE6d/fN1RR9pUwmvxVzOKgn1TWpcyCuvtoYbm8BW3q6HXOoDtDi1lMF6Jffl+QismG83iO906WYYYaGoNtDEinIMRfyKn5K9HXVOqsh+QhqA2HC+NQdEghM8AjIbCR1j7AUizd9XIUri5ciQvPrlQskJZDoq07lD6eLgX3mvxRBlK57THcT83bJ2N8DMLxEwQPx+GEM9729mDQFBhFlx7F7ZueeZzJbVo0PtvrtpvV03Y0wr/lC60f986JMdtJI9tBqadffARpSz6jSd4DdFZPJeROTXCXasSl+to=
  on:
    tags: true
